<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-4IQHI62" name="com.wooplr.ecomproduct.test.EcomProductTestPlan" tests="15" failures="1" timestamp="2 Dec 2016 10:14:08 GMT" time="93.165" errors="2">
  <testcase name="updateProduct" time="5.143" classname="com.wooplr.ecomproduct.test.EcomProductTestPlan"/>
  <testcase name="deleteProduct" time="5.062" classname="com.wooplr.ecomproduct.test.EcomProductTestPlan">
    <error type="java.lang.AssertionError" message="Expected to throw 204 status, but it thrown: 200 Status Message: OK expected [204] but found [200]">
      <![CDATA[java.lang.AssertionError: Expected to throw 204 status, but it thrown: 200 Status Message: OK expected [204] but found [200]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:370)
	at com.wooplr.consumers.EcomProductConsumer.getProduct(EcomProductConsumer.java:84)
	at com.wooplr.ecomproduct.test.EcomProductTestPlan.deleteProduct(EcomProductTestPlan.java:137)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:696)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:1027)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1207)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:38)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:382)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- deleteProduct -->
  <testcase name="createProduct" time="11.847" classname="com.wooplr.ecomproduct.test.EcomProductTestPlan"/>
  <testcase name="updateProduct" time="4.685" classname="com.wooplr.ecomproduct.test.EcomProductTestPlan"/>
  <testcase name="createProduct" time="5.785" classname="com.wooplr.ecomproduct.test.EcomProductTestPlan"/>
  <testcase name="updateProduct" time="4.921" classname="com.wooplr.ecomproduct.test.EcomProductTestPlan"/>
  <testcase name="updateSkuDetails" time="1.442" classname="com.wooplr.ecomproduct.test.EcomProductTestPlan">
    <failure type="java.util.ConcurrentModificationException">
      <![CDATA[java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(Unknown Source)
	at java.util.ArrayList$Itr.next(Unknown Source)
	at com.wooplr.ecomproduct.test.EcomProductTestPlan.updateSkuDetails(EcomProductTestPlan.java:153)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:696)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:1027)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1207)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:38)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:382)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- updateSkuDetails -->
  <testcase name="updateProduct" time="10.992" classname="com.wooplr.ecomproduct.test.EcomProductTestPlan"/>
  <testcase name="createProduct" time="11.122" classname="com.wooplr.ecomproduct.test.EcomProductTestPlan"/>
  <testcase name="updateProduct" time="6.213" classname="com.wooplr.ecomproduct.test.EcomProductTestPlan"/>
  <testcase name="createProduct" time="4.421" classname="com.wooplr.ecomproduct.test.EcomProductTestPlan"/>
  <testcase name="createProduct" time="10.004" classname="com.wooplr.ecomproduct.test.EcomProductTestPlan"/>
  <testcase name="updateProduct" time="7.272" classname="com.wooplr.ecomproduct.test.EcomProductTestPlan"/>
  <testcase name="getProduct" time="3.385" classname="com.wooplr.ecomproduct.test.EcomProductTestPlan"/>
  <testcase name="getByInvalidProductId" time="0.871" classname="com.wooplr.ecomproduct.test.EcomProductTestPlan">
    <error type="java.lang.AssertionError" message="Expected to throw 204 status, but it thrown: 500 Status Message: Internal Server Error expected [204] but found [500]">
      <![CDATA[java.lang.AssertionError: Expected to throw 204 status, but it thrown: 500 Status Message: Internal Server Error expected [204] but found [500]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:370)
	at com.wooplr.consumers.EcomProductConsumer.getProduct(EcomProductConsumer.java:84)
	at com.wooplr.ecomproduct.test.EcomProductTestPlan.getByInvalidProductId(EcomProductTestPlan.java:93)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:696)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:1027)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1207)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:38)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:382)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- getByInvalidProductId -->
</testsuite> <!-- com.wooplr.ecomproduct.test.EcomProductTestPlan -->
